### ISSUE TITLE
Too slow!

### ISSUE THREAD

**Issue by linonetwo** [bimlas/tw5-kin-filter#1]
See Jermolene/TiddlyWiki5#7151

Can there be a lighter version of kin-filter that only capable of finding tag tree?

Seems finding `list` field and shadow tiddlers cost too much of computation, which is not a part of finding tags of tags.

**Comment by linonetwo** [comment]
An very fast alternative, if you only need `kin::to[xxx]`!

https://github.com/tiddly-gittly/in-tagtree-of

https://tiddly-gittly.github.io/in-tagtree-of/

**Comment by bimlas** [comment]
@linonetwo 

Sorry for the late reply. Thanks for the links! :+1:

I've updated and hopefully fixed the performance issue in Kin plugin. Can you test it again please?

**Comment by linonetwo** [comment]
I see, glad to hear that! Caches are cool!
